baseURL               = "https://navi.xzgljiang.com/"
languageCode          = "zh-CN"
title                 = "JiAngの导航站"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"					# 站点静态文件保存目录


[params]
    author        = "shenweiyan"
    description   = "xzgl 导航小站"
    siteurl       = "./"
    upload        = "document"                                          # 左侧导航栏的"网站提交"
    leisure       = "leisure"
    about         = "https://shumlab.com/cookbook/webstack-hugo"	    # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"  
    enablePreLoad = true					                            # 网站完全打开前预加载动画
    textPreLoad   = ">>> xzgl Loading >>>"				                # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					                            # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			                    # 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/default_logo.png"		            # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					                            # 默认站点为深色(夜间)模式
    collectShow   = true                                                # 显示收藏链接( collect.yml 中的链接)
    collectCount  = 5                                                   # 显示收藏链接数量
	
[params.seo]    
    baiduhmid     = 'efccc04cb44fc49faddac5876180b369'		            # 百度统计 hm.src 的 ID
    baiduSiteVer  = 'codeva-cCAOSG8MBO'				                    # 百度HTML标签验证(baidu-site-verification)

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/cat.png"
    searchImageL      = "assets/images/bg-light.jpg"		            # 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dark.jpg"		                # 搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand.png"
    logoExpandDark    = "assets/images/bt8-expand.png"
    logoCollapseLight = "assets/images/cat.png"
    logoCollapseDark  = "assets/images/cat.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：linxzgl@gmail.com &nbsp;<a target="_blank" href="https://github.com/ihavenoideaa/nav-Pages"><i style="font-size:0.8rem;margin-right:2px" class="fas fa-code"></i>本站源码</a> <br/>&copy; Copyright 2023 xzgl. Powered By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | <a target="_black" style="white-space: nowrap;" href="http://beian.miit.gov.cn/">粤ICP备2023008974号</a> | '
